# Generated by Django 4.1.5 on 2023-01-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('courseNum', models.IntegerField()),
                ('course_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='courseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseComplexity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('CourseFamiliarity', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='courseDidactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseComplexity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('CourseFamiliarity', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='courseImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='courseLectTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='coursePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.DecimalField(decimal_places=2, max_digits=2)),
                ('time0', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pres0', models.DecimalField(decimal_places=2, max_digits=2)),
                ('complexity', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='courseStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hei_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=250)),
                ('lecturer_title', models.CharField(max_length=250)),
                ('courseOffered', models.ManyToManyField(blank=True, null=True, to='timeOptimizer.course')),
            ],
        ),
        migrations.CreateModel(
            name='optData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterName', models.CharField(max_length=250)),
                ('totalHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('optMethod', models.CharField(choices=[('product', 'product'), ('sum', 'sum'), ('sqrt', 'sqrt'), ('min', 'min')], max_length=10)),
                ('courses', models.JSONField(blank=True, default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeOptimizer.lecturer')),
                ('picked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeOptimizer.course')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=250)),
                ('semesterModules', models.JSONField()),
                ('coursesInSemester', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='optResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('veryGood', 'Very Good'), ('good', 'Good'), ('ok', 'Ok'), ('bad', 'Bad')], max_length=20)),
                ('semesterName', models.CharField(max_length=250)),
                ('totalHours', models.FloatField()),
                ('optMethod', models.CharField(max_length=10)),
                ('optimalValue', models.FloatField(default=0.0)),
                ('optimizationResults', models.JSONField()),
                ('optDataObj', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opt_results', to='timeOptimizer.optdata')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseContent_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.coursecontent'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseDidactic_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.coursedidactic'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseImpact_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.courseimpact'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseLectTime_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.courselecttime'),
        ),
        migrations.AddField(
            model_name='course',
            name='coursePresentation_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.coursepresentation'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseStudentCount_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeOptimizer.coursestudentcount'),
        ),
    ]
