# Generated by Django 4.1.5 on 2023-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0003_optresults_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='optdata',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optdata',
            name='status',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='optresults',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optresults',
            name='status',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
