# Generated by Django 4.1.5 on 2023-04-05 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0002_alter_optdata_lecturer_alter_optdata_totalhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='optresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
