# Generated by Django 4.1.5 on 2023-04-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0004_optdata_edited_at_optdata_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optresults',
            name='update_status',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
