# Generated by Django 4.1.5 on 2023-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0012_alter_optdata_optmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optresults',
            name='optMethod',
            field=models.CharField(max_length=20),
        ),
    ]
