# Generated by Django 4.1.5 on 2023-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0018_alter_optdata_lecturer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='coursesInSemester',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterModules',
            field=models.JSONField(default=dict),
        ),
    ]
