# Generated by Django 4.1.5 on 2023-05-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0022_optdata_weight_category_alter_optdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='optdata',
            name='clone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
