# Generated by Django 4.1.5 on 2023-08-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0024_alter_lecturer_time_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='profile_picture',
        ),
    ]
