# Generated by Django 4.1.5 on 2023-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0005_optresults_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.ImageField(default='default_pro_pic.jpg', upload_to='profile_pics'),
        ),
    ]
