# Generated by Django 4.1.5 on 2023-04-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0011_lecturer_lecturer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optdata',
            name='optMethod',
            field=models.CharField(choices=[('product', 'product'), ('sum', 'sum'), ('sqrt', 'sqrt'), ('min', 'min'), ('weightedAverage', 'weightedAverage')], max_length=20),
        ),
    ]
