# Generated by Django 4.1.5 on 2023-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0013_alter_optresults_optmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseContent_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseDidactic_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseImpact_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseLectTime_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseNum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursePresentation_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseStudentCount_data',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer_name',
            field=models.CharField(default='Anonymous Lecturer', max_length=250),
        ),
    ]
