# Generated by Django 4.1.5 on 2023-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0017_remove_optdata_eval_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optdata',
            name='lecturer_category',
            field=models.CharField(choices=[('#', '#'), ('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], default='#', max_length=20),
        ),
    ]
