# Generated by Django 4.1.5 on 2023-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0019_alter_semester_coursesinsemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='coursesInSemester',
            field=models.JSONField(default={'': {}}),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterModules',
            field=models.JSONField(default={'': {}}),
        ),
    ]
