# Generated by Django 4.1.5 on 2023-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0020_alter_semester_coursesinsemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='time_available',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
