# Generated by Django 4.1.5 on 2023-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0021_alter_lecturer_time_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='optdata',
            name='weight_category',
            field=models.CharField(choices=[('0', '0'), ('high_W', 'high_W'), ('mid_W', 'mid_W'), ('low_W', 'low_W'), ('rand_W', 'rand_W')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='optdata',
            name='status',
            field=models.CharField(default='probably a copy', max_length=50),
        ),
    ]
