# Generated by Django 4.1.5 on 2023-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeOptimizer', '0023_optdata_clone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='time_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
